language: node_js
node_js:
  12.18.3
install:
  - npm install serverless -g
  - npm install
  - npm install --save serverless-webpack
  - npm install --save serverless-reqvalidator-plugin
  - npm install --save serverless-aws-documentation
  - npm install --save serverless-iam-roles-per-function
  - npm install --save serverless-plugin-tracing
after_success:
  - serverless deploy -v